# @package _global_

defaults:
  - masked_mimic/base
  - /terrain/complex

# Fabric configuration
fabric:
  _target_: lightning.fabric.Fabric
  _convert_: all
  accelerator: gpu
  devices: 1
  num_nodes: 1
  strategy:
    _target_: lightning.fabric.strategies.DDPStrategy
  precision: 32-true
  loggers: null

# Override agent to use masked mimic
agent:
  _target_: protomotions.agents.masked_mimic.agent.MaskedMimic
  _recursive_: False
  config:
    expert_model_path: null  # No expert model needed for evaluation
    vae:
      noise_type: "zeros"  # Use deterministic behavior for evaluation

# Environment configuration for mimic (required for masked_mimic agent)
env:
  config:
    max_episode_length: 300
    enable_height_termination: True
    # The mimic environment will provide the required masked_mimic observations
    mimic_target_pose:
      enabled: true
      type: max-coords-future-rel
      with_time: true
      num_future_steps: 15
    masked_mimic:
      enabled: true
      masked_mimic_masking:
        joint_masking:
          masked_mimic_time_gap_probability: 0.1
          time_gap_mask_min_steps: 1
          time_gap_mask_max_steps: 11
          with_conditioning_time_gap_mask_max_steps: 44
          with_conditioning_max_gap_probability: 0.2
          masked_mimic_repeat_mask_probability: 0.98
          masked_mimic_fixed_conditioning: null
          force_max_conditioned_bodies_prob: 0.1
          force_small_num_conditioned_bodies_prob: 0.1
        target_pose_visible_prob: 0.2
        motion_text_embeddings_visible_prob: 0
      masked_mimic_target_pose:
        num_obs_per_sparse_target_pose: 264
        num_future_steps: 10
        num_obs_per_joint: 24
        num_obs_per_target_pose: 432
      motion_text_embeddings:
        enabled: false
        embedding_dim: 512
      historical_obs:
        num_historical_conditioned_steps: 15
    humanoid_obs:
      num_historical_steps: 120

# Evaluation overrides
eval_overrides:
  agent:
    config:
      expert_model_path: null
      vae:
        noise_type: "zeros"  # Deterministic evaluation
  env:
    config:
      max_episode_length: 10000
      enable_height_termination: True
  num_envs: 1
  headless: false

# Global parameters
ngpu: 1
nodes: 1
torch_deterministic: false
amp_precision: 32-true

# Checkpoint path (will be overridden by command line)
checkpoint: ???

# Display settings
headless: false

# Experiment settings
experiment_name: masked_mimic_eval

# Motion file (required for masked_mimic agent)
motion_file: data/motions/smpl_humanoid_walk.npy

# Motion synchronization
sync_motion: false

# Training parameters
training_max_steps: 1000000 