# @package _global_

defaults:
  - masked_mimic/base
  - /env/steering
  - /terrain/complex
  - _self_

# Training-specific overrides
agent:
  config:
    expert_model_path: data/pretrained_models/masked_mimic/smpl  # Path to pretrained expert model
    vae:
      noise_type: "normal"  # Use normal noise during training
    # Training parameters
    num_steps: 32
    batch_size: 1024
    num_mini_epochs: 6
    eval_metrics_every: 500
    manual_save_every: 10
    max_epochs: ${eval:${training_max_steps}//${ngpu}//${num_envs}//${.num_steps}}

# Environment configuration for steering training
env:
  config:
    max_episode_length: 1000
    enable_height_termination: True
    steering_params:
      heading_change_steps_min: 40
      heading_change_steps_max: 150
      random_heading_probability: 0.2
      standard_heading_change: 1.57
      tar_speed_min: 1.2
      tar_speed_max: 6
      standard_speed_change: 0.3
      stop_probability: 0.05
      obs_size: 3

# Training parameters
num_envs: 4
training_max_steps: 10000000
experiment_name: masked_mimic_steering_training
headless: true

# Motion file (required for masked_mimic agent)
motion_file: data/motions/smpl_humanoid_walk.npy
sync_motion: false

# Global parameters
ngpu: 1
nodes: 1
torch_deterministic: false
amp_precision: 32-true 