# @package _global_

defaults:
  - /agent/ppo/agent

agent:
  _target_: protomotions.agents.amp.agent_with_expert.AMPWithExpert
  _recursive_: False
  config:
    # Setup discriminator structure
    model:
      _target_: protomotions.agents.amp.model.AMPModel  # Override main model
    # AMP parameters
    task_reward_w: 0.0

    discriminator_weight_decay: 0.0001
    discriminator_logit_weight_decay: 0.01
    discriminator_batch_size: 1024
    discriminator_reward_w: 1.0
    discriminator_grad_penalty: 5
    discriminator_replay_keep_prob: 0.01
    discriminator_replay_size: 200000
    num_discriminator_mini_epochs: 3

    # Expert model path for loading pretrained models
    expert_model_path: ??? 